### ISSUE TITLE
SetPrintStringFunction is not working

### ISSUE THREAD

**Issue by ccerhan** [ccerhan/LibSVMsharp#1]
Hello,

The SVM.SetPrintStringFunction, which corresponds to the svm_set_print_string_function in libsvm, is not working. Normally, the output string is logged on the console (stdout) while training is going on. 

``` C++
// Default print function in libsvm
static void print_string_stdout(const char *s)
{
    fputs(s,stdout);
    fflush(stdout);
}

// The original function located in libsvm
void svm_set_print_string_function(void (*print_func)(const char *))
{
    if(print_func == NULL)
        svm_print_string = &print_string_stdout;
    else
        svm_print_string = print_func;
}
```

The problem is that I could not change the function pointer from C# layer. I set a delegate pointer for the callback. When I am in debug mode, I can go into the callback function I defined. However, when I continue (pressing F5), the console which I executed the test program is suddenly terminated without an error. The test code is shown below.

``` C#
static void Main(string[] args)
{
      SVM.SetPrintStringFunction(new SVMPrintFunction(Output));
      // some code ...
      SVMModel model = SVM.Train(problem, parameter); // Logging is started here
      // some code ....
}

public static void Output(string log) // I can see the log value in the first time in debug mode
{
       Console.WriteLine(""); // DEBUG POINT
}
```

Please solve this issue, and send a pull request.

Can Erhan.

**Comment by spzenk** [comment]
public static SVMPrintFunction mySVMPrintFunction = new SVMPrintFunction(Output);

private static void Output(string log) // I can see the log value in the first time in debug mode
{
    //Console.WriteLine(""); // DEBUG POINT
}

and... 

SVM.SetPrintStringFunction(mySVMPrintFunction);

u can suppress output..

**Comment by ccerhan** [comment]
Thank you @spzenk, it is now working !
Issue closed.
