### ISSUE TITLE
 Marshal.FreeHGlobal(x.rho) got unknown error

### ISSUE THREAD

**Issue by LibnizLin** [ccerhan/LibSVMsharp#11]
I have a SVM model, name as insulin_model.txt. When I execute the below code: 

```
        //Load the model
        SVMModel load_model  = SVM.LoadModel(@"insulin_model.txt");
        //Set SVMNode values
        SVMNode[] nodes = new SVMNode[8];
        nodes[0] = new SVMNode(1, -0.628);
        nodes[1] = new SVMNode(2, -0.818);
        nodes[2] = new SVMNode(3, -0.778);
        nodes[3] = new SVMNode(4, -0.333);
        nodes[4] = new SVMNode(5, -0.093);
        nodes[5] = new SVMNode(6, -0.941);
        nodes[6] = new SVMNode(7, -0.88);
        nodes[7] = new SVMNode(8, 0.336);

        double[] predict_values;
        double _r = SVM.PredictProbability(load_model, nodes, out predict_values);
        Console.WriteLine("SVM.PredictProbability:" + _r.ToString());
```

I got Marshal.FreeHGlobal(x.rho)  unknown error. I am very pleasure that  someone can help me. Thanks.

**Comment by zengfr** [comment]
parameter.Probability = true;

**Comment by LibnizLin** [comment]
Thanks for zengfr's help.
Is there a complete example code to set "parameter.Probability = true;"  when I  used in loading model stage. Thanks

**Comment by zengfr** [comment]
SVMParameter parameter=new SVMParameter();
parameter.Probability = true;

var model=SVM.Train(problem,parameter);

**Comment by zengfr** [comment]
you can see in my projects :  https://github.com/zengfr/SVM-Neuro-Matching
https://github.com/zengfr/SVM-Neuro-Matching/blob/master/roomMatching/roomMatching/Program.cs

**Comment by LibnizLin** [comment]
Thanks for zengfr's help. Your code is good for me. Thanks.
