### ISSUE TITLE
is a  The endless loop in class SVMModelExtensions

### ISSUE THREAD

**Issue by zengfr** [ccerhan/LibSVMsharp#12]
it is a The endless loop , in class SVMModelExtensions model.PredictValues  
public static class SVMModelExtensions
    {
        public static double PredictValues(this SVMModel model, SVMNode[] x, out double[] values)
        {
            return model.PredictValues(x, out values);
        }

**Comment by ccerhan** [comment]
Hello, 

Sorry for the late answer. I think this problem is fixed by [this commit](https://github.com/ccerhan/LibSVMsharp/commit/e45ec4088a328b58cdd00ce89a0ed1b6a4389f18). 

Thank you
