### ISSUE TITLE
IS there a x64 version?

### ISSUE THREAD

**Issue by CBrauer** [ccerhan/LibSVMsharp#2]
I'm running on Windows 8.1 with Visual Studio 2013 on an x64 (I7) machine.  I had to build and run with a platform target of x32 to make it work.

Is there a x64 release?

Thanks in advance.

Charles

**Comment by ccerhan** [comment]
Hello Charles,

This library supports only the x86 version of libsvm.
I am waiting for the official x64 version.

See this [link](https://github.com/cjlin1/libsvm/issues/17) for more information.
If you want to use x64 version of it, you have to build yourself as you did.

Kind regards,

Can Erhan.

**Comment by CBrauer** [comment]
Hello Can,

Thank you for the quick reply. I have decided to build the x64 version starting from the C# version:

   http://www.matthewajohnson.org/software/svm.html

Charles

**Comment by ccerhan** [comment]
Hello Charles,

This is a C# wrapper for java port of libsvm. It works slower than C# wrapper for libsvm directly. 
My suggestion is that build the x64 version of libsvm, download the nuget package of LibSVMsharp and replace the libsvm dll.

Regard,

Can Erhan.

**Comment by CBrauer** [comment]
Hello Can,

Thanks for your comment.  Bye the way, what do you think of Cesar Souza's work on Accord.NET Framework, which includes an SVM implementation?

Charles
