### ISSUE TITLE
libsvmsharp-64bit

### ISSUE THREAD

**Issue by saifmohammed** [ccerhan/LibSVMsharp#22]
hello every one..... please can any one help me in use the "libsvmsharp-64bit" in satellite image classification and explain me the step by step ..... thanks for your answer previously 
best regards

**Comment by ccerhan** [comment]
For technical details like how to use libsvm or more basically how to use support vector machines, you may want to check [official libsvm page](https://www.csie.ntu.edu.tw/~cjlin/libsvm/).
