### ISSUE TITLE
NullReferenceException When call "svm_node node = (svm_node)Marshal.PtrToStructure(i_ptr_nodes, typeof(svm_node));"

### ISSUE THREAD

**Issue by HardworkingPearl** [ccerhan/LibSVMsharp#26]
I am tring to read a trained SVM model in unity. It's quite strange here, sometimes i could successfully read the model but sometime it gives me an error for:

> "NullReferenceException: Object reference not set to an instance of an object"

The error occurs at this line:

`svm_node node = (svm_node)Marshal.PtrToStructure(i_ptr_nodes, typeof(svm_node));`

The whole function is:

```
public static SVMNode[] Convert(IntPtr ptr)
{
	if (ptr == IntPtr.Zero)
		return null;

	List<SVMNode> nodes = new List<SVMNode>();
	IntPtr i_ptr_nodes = ptr;
	while (true)
	{
		svm_node node = (svm_node)Marshal.PtrToStructure(i_ptr_nodes, typeof(svm_node));
		i_ptr_nodes = ptrExtentions.Add(i_ptr_nodes, Marshal.SizeOf(typeof(svm_node)));
		if (node.index > 0)
		{
			nodes.Add(new SVMNode(node.index, node.value));
		}
		else
		{
			break;
		}
	}

	return nodes.ToArray();
}
```

The whole track is:

> NullReferenceException: Object reference not set to an instance of an object
>   at (wrapper unknown) intptr:PtrToStructure (intptr,object)
>   at (wrapper managed-to-native) System.Runtime.InteropServices.Marshal:PtrToStructure (intptr,System.Type)
>   at LibSVMsharp.SVMModel.Convert (svm_model x) [0x003a7] in D:\AttentionDemo-copy\racing-game-course-csharp\Assets\Libsvm\SVMModel.cs:205 
>   at LibSVMsharp.SVMModel.Convert (IntPtr ptr) [0x0002f] in D:\AttentionDemo-copy\racing-game-course-csharp\Assets\Libsvm\SVMModel.cs:219 
>   at LibSVMsharp.SVM.LoadModel (System.String filename) [0x00053] in D:\AttentionDemo-copy\racing-game-course-csharp\Assets\Libsvm\SVM.cs:177 
>   at RunOnlineTraining.run_online_training (System.String inDataPath, System.String mdlPath, System.String cfgPath) [0x001e1] in D:\AttentionDemo-copy\racing-game-course-csharp\Assets\Scripts\RunOnlineTraining.cs:113 
>   at CalibManager.trainModel () [0x00016] in D:\AttentionDemo-copy\racing-game-course-csharp\Assets\Scripts\CalibManager.cs:533 
>   at CalibManager.FinishSession () [0x00279] in D:\AttentionDemo-copy\racing-game-course-csharp\Assets\Scripts\CalibManager.cs:519 
>   at CalibManager.Update () [0x000d4] in D:\AttentionDemo-copy\racing-game-course-csharp\Assets\Scripts\CalibManager.cs:102 
>  
> (Filename: D:/AttentionDemo-copy/racing-game-course-csharp/Assets/Libsvm/SVMModel.cs Line: 205)

I have been stuck here for quite long time. If anyone has any suggestion, it would be a great appreciate.

**Comment by mmehrle** [comment]
See below - I don't know if svm_node is a global, but if it isn't then 
you are passing in an object into typeof that has not yet been 
initialized yet.

**Comment by HardworkingPearl** [comment]
@mmehrle svm_node is a "structure" defined in "LibSVMsharp.Core". I think the problem exists in the ptr "i_ptr_nodes". thank you btw.

**Comment by HardworkingPearl** [comment]
Solved. For c# implementation, please use at least NET 4.0
