### ISSUE TITLE
Unable to train with SVMType NU_SVR, EPSILON_SVR or ONE_CLASS

### ISSUE THREAD

**Issue by saffsd** [ccerhan/LibSVMsharp#3]
Here's a minimal snippet to reproduce the problem:

```
    private static void Main(string[] args)
    {
        SVMProblem testSet = SVMProblemHelper.Load(@"Dataset\wine.txt"); 
        var x = testSet.Train(new SVMParameter{Type=SVMType.ONE_CLASS});
    }
```

This fails in `SVMModel Convert(svm_model x)`, at

```
        y.SVCounts = new int[y.ClassCount];
        Marshal.Copy(x.nSV, y.SVCounts, 0, y.SVCounts.Length);

        y.Labels = new int[y.ClassCount];
        Marshal.Copy(x.label, y.Labels, 0, y.Labels.Length);
```

because both x.nSV and x.label are 0 (null pointers).

I don't think it's a problem with the data because CrossValidation does not have a similar issue:

```
    private static void Main(string[] args)
    {
        SVMProblem testSet = SVMProblemHelper.Load(@"Dataset\wine.txt"); 
        double[] target;
        testSet.CrossValidation(new SVMParameter{Type=SVMType.ONE_CLASS}, 5, out target);
    }
```

I've tried to debug it myself with no success, it's not clear to me why LibSVM is returning null pointers for nSV and label.

**Comment by saffsd** [comment]
From the libsvm source, it looks like these values are meant to be null in SVR:

https://github.com/cjlin1/libsvm/blob/master/svm.cpp

```
if(param->svm_type == ONE_CLASS ||
   param->svm_type == EPSILON_SVR ||
   param->svm_type == NU_SVR)
{
    // regression or one-class-svm
    model->nr_class = 2;
    model->label = NULL;
    model->nSV = NULL;
    model->probA = NULL; model->probB = NULL;
    model->sv_coef = Malloc(double *,1);
```

I've put together a patch that seems to work, I'll set up a pull request.

**Comment by ccerhan** [comment]
Hello saffsd,

You are absolutely right !
I have never used one class svm, just implemented as the others. 
I merged your pull request, and I updated the nuget package to 1.2.2.

Thanks a lot to fix this issue,

Can Erhan
