### ISSUE TITLE
how to use x64 libsvm and some other questions

### ISSUE THREAD

**Issue by MonsterMMORPG** [ccerhan/LibSVMsharp#6]
Hello. I have downloaded libSVMsharp

And i downloaded latest libsvm dll (http://www.csie.ntu.edu.tw/~cjlin/cgi-bin/libsvm.cgi?+http://www.csie.ntu.edu.tw/~cjlin/libsvm+zip) and replace it with libSVMsharp dll

the below code works fine at x86 application

```
        SVMProblem problem = SVMProblemHelper.Load(@"train.txt");
        SVMProblem testProblem = SVMProblemHelper.Load(@"test.txt");

        SVMParameter parameter = new SVMParameter();
        parameter.Type = SVMType.C_SVC;
        parameter.Kernel = SVMKernelType.RBF;
        parameter.C = 1;
        parameter.Gamma = 1;

        SVMModel model = SVM.Train(problem, parameter);

        double[] target = new double[testProblem.Length];
        for (int i = 0; i < testProblem.Length; i++)
            target[i] = SVM.Predict(model, testProblem.X[i]);

        double accuracy = SVMHelper.EvaluateClassificationProblem(testProblem, target);
```

however when i turn my c# 4.5.2 WPF application to x64 it fails. where can i find x64 version of this dll?

or how can i make it work?

Now the other thing is i want to do cross validation to find best parameters

How do i do it? i could not find any example on your github

can you write me example to Use cross-validation to find the best parameter C and γ

**Comment by ccerhan** [comment]
Hello,

Check [this](https://github.com/ccerhan/LibSVMsharp/issues/2) link for building the x64 version of the library manually.

To choose the parameter set giving the best results according to your dataset, you can iterate SVM.CrossValidation method with several parameter sets.

For example:

``` C#
SVMParameter parameter = new SVMParameter();
parameter.Type = SVMType.C_SVC;
parameter.Kernel = SVMKernelType.RBF;

IList<double> cValuesToTry = new List<double>() { 0.1, 1, 10, 100 };

double maxAccuracy = -1;
double bestCvalue = 0;
for (int i = 0; i < cValuesToTry.Count; i++)
{
     parameter.C = cValuesToTry[i];

     double[] crossValidationResults; // output labels
     trainingSet.CrossValidation(parameter, nFold, out crossValidationResults);

     // Evaluate the cross validation result
     double crossValidationAccuracy = trainingSet.EvaluateClassificationProblem(crossValidationResults);

     if (crossValidationAccuracy > maxAccuracy)
     {
          maxAccuracy = crossValidationAccuracy;
          bestCvalue = cValuesToTry[i];
     }
}

parameter.C = bestCvalue;
SVMModel model = trainingSet.Train(parameter);
```

If you want to choose gamma also, you should use nested for loops. One of them is for C, the other one is for gamma. 

Regards,

Can Erhan.

**Comment by MonsterMMORPG** [comment]
Dear Can ty very much for answer. I generated the x64 dll with following instructions. However i am getting this error with x64 dll

here the dll file : http://www.mediafire.com/download/poqx5rn3aax2ja7/libsvm.dll

I installed LibSVMsharp via nuget package and changed nothing other than dll file

Here the error i am getting

![x64 error](https://cloud.githubusercontent.com/assets/4149474/10430979/ee961468-710a-11e5-8f30-b4c05dda5dec.png)

**Comment by aschoenauer-sebag** [comment]
Hi,

Just to let you know that if you clone the repo and build LibSVMSharp yourself, then reference this dll in your project it works (after uninstalling the nuget version).

Cheers,
Alice

**Comment by MonsterMMORPG** [comment]
Hi lalil0u ty for reply. yes that is how i solved. still  giving errors in some occasions and no multi threading :(

**Comment by ccerhan** [comment]
A new version of official libsvm is released with x64 support several days ago.
Change log can be found at the most bottom of the [page](https://www.csie.ntu.edu.tw/~cjlin/libsvm/log).

I will not update the library now, because if you use the new dll file on your project, you will not able to use it in x32 platform anymore. I changed the dll file to the new x64 one and I always got BadImageFormatException until I configure platform target to x64 for both the library and the application projects.

You don't have to compile libsvm project for x64 anymore. Just configure platform target to x64 and replace libsvm.dll that is downloaded from [official libsvm project](https://github.com/cjlin1/libsvm/tree/master/windows)

**Comment by MonsterMMORPG** [comment]
ccerhan currently i am using x64. i did built it myself. however as i said, no multi threading support and several things causes errors. but ty for letting me know.

**Comment by MonsterMMORPG** [comment]
by the way new dll seems like faster than older one :)

**Comment by ccerhan** [comment]
From now on, only x64 version of libsvm will be supported as in official libsvm releases.
